language: android
android:
  components:
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
